### ISSUE TITLE
image does not appear

### ISSUE THREAD

**Issue by kanjeng1** [fakhrirobi/whatsapp_broadcast#1]
Hi, there is an issue on "Usage Documenation :" it seems the image (.gif) does not appear also when i clicked it shows "page not found". here i attached the screenshot
<img width="960" alt="Screenshot 2021-04-16 072712" src="https://user-images.githubusercontent.com/82664505/115040237-12042580-9e86-11eb-90df-dacea93ce814.png">

**Comment by kanjeng1** [comment]
also After python installed, Then Click Windows Button + R to run Command Prompt (CMD) and paste this code

python get-pip.py

i got this error 
<img width="671" alt="Screenshot 2021-04-16 073638" src="https://user-images.githubusercontent.com/82664505/115040617-7cb56100-9e86-11eb-955b-d22e48b50b4c.png">

**Comment by fakhrirobi** [comment]
Thank you very much for the feedback I recently just updated the readme file
