### ISSUE TITLE
Broadcast not working

### ISSUE THREAD

**Issue by Anil2710** [fakhrirobi/whatsapp_broadcast#2]
Not working sir. I am sharing the screenshot of run window.
![Screenshot (6)](https://user-images.githubusercontent.com/62250590/121539544-63aed380-ca23-11eb-9cd5-909cb9383718.png)

**Comment by fakhrirobi** [comment]
oke thanks for your feedback. i will check my code again

**Comment by Anil2710** [comment]
Sir can u give ur contact any social media so i can explain my issue
completely.

**Comment by fakhrirobi** [comment]
i have twitter account. it is @fakhrirobiaulia

**Comment by Anil2710** [comment]
Sir will you clear my error actually that run broadcast button not working.

Anil

**Comment by fakhrirobi** [comment]
i just updated the code bro.

**Comment by Anil2710** [comment]
Ok sir let me check and will you update it. Thank you sir

**Comment by Anil2710** [comment]
Sir it is not working will you give me correct explaination. I am sharing my issue in video which i shared below a link.

https://drive.google.com/file/d/1T1i01xAfZZC4GQBDyEJhRrarlLoSwXeu/view?usp=sharing

**Comment by fakhrirobi** [comment]
um can u show me the pandas version? i recommend you to uninstall the pandas first and install the latest.

**Comment by Anil2710** [comment]
Ok, I will.

**Comment by Anil2710** [comment]
![Screenshot (11)](https://user-images.githubusercontent.com/62250590/124235343-bebf7c00-db32-11eb-89d5-4068539f83ba.png)

i installed later version of pandas but when i am running the program it throws errors.
