### ISSUE TITLE
Broadcast attachment not working

### ISSUE THREAD

**Issue by Anil2710** [fakhrirobi/whatsapp_broadcast#3]
![Screenshot (13)](https://user-images.githubusercontent.com/62250590/124361239-ad1dc780-dc4b-11eb-9210-e0722ddcd111.png)

Bro Could You show one live demo of your project.so it will clarify my error. In below i am sharing video link  & code file not working

https://drive.google.com/drive/folders/1k9rqq2uozhxuF4tHYau4TEgtyk6cIp0_?usp=sharing
[whatsapp_broadcast-main.zip](https://github.com/fakhrirobi/whatsapp_broadcast/files/6758734/whatsapp_broadcast-main.zip)

**Comment by fakhrirobi** [comment]
umm please clone again  my github repo. from the screen shot it looks like you have not followed my latest commit

**Comment by Anil2710** [comment]
![Screenshot (14)](https://user-images.githubusercontent.com/62250590/124389327-31cc1c80-dd04-11eb-9455-58dfb1572db4.png)

**Comment by fakhrirobi** [comment]
oh i realized that i forget to delete Chrome Options Line. just fetch again the scrapper.py bro. Thanks a lot for your feedbackk

**Comment by Anil2710** [comment]
Bro can u show me live demo because i am facing errors from past 3 weeks.Will you Please help me.
![bb](https://user-images.githubusercontent.com/62250590/124636418-257fc500-dea6-11eb-824c-91ffa6320d58.png)

**Comment by fakhrirobi** [comment]
umm bro maybe you should clone again my repo since my latest repo does not contain lamba function again

**Comment by Anil2710** [comment]
Good morning bro but I checked there is lambda. And i want  you to know that message with attachment functionality not working. ahh when will you be free so you can connect with anydesk and check it.Its a humble request bro.
![Screenshot (21)](https://user-images.githubusercontent.com/62250590/125181732-7afcfe80-e225-11eb-9bd8-10ae771fcdbb.png)
